version: '3.8'

services:
  vite-http:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CONFIG: vite.config.http.js
    ports:
      - "5174:5174"
    environment:
      - NODE_ENV=production
    command: npx vite preview --host --port 5174

  vite-https:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CONFIG: vite.config.https.js
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    command: npx vite preview --host --port 5173
