version: '3.8'

services:
  webapp:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - ..:/app:cached
    ports:
      - "5174:5174"
    command: /bin/sh -c "npm run build && npx vite preview --host 0.0.0.0 --port 5174 --outDir www --config vite.config.http.js"